let perfilVol = [
    {
      id: 1,
      nome: "NOME USUÁRIO",
      email: "usuario@email.com",
      senha: "senha12345",
      textoBio: "Uma breve descrição do usuário",
      imagemPerfil: "img/foto-perfil.png",
      tabelaInteresses: "interesses",
      experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
      qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
    },
    {
        id: 2,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 3,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 4,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 5,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 6,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 7,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 8,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 9,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
      {
        id: 10,
        nome: "NOME USUÁRIO",
        email: "usuario@email.com",
        senha: "senha12345",
        textoBio: "Uma breve descrição do usuário",
        imagemPerfil: "img/foto-perfil.png",
        tabelaInteresses: "interesses",
        experiencias: ["Nome", "Área de atuação", "Local", "Cargo", "Descrição", "Data"],
        qualificacao: ["Nome", "Tipo", "Instituição", "Área", "Período"],
      },
  ];
  
  localStorage.clear();
  localStorage.setItem("perfilVol", JSON.stringify(perfilVol));
  
  if (localStorage.getItem("perfilVol") != null)
    document.querySelector("#resultado").innerHTML = "Base de dados criada";
  else 
    document.querySelector("#resultado").innerHTML = "Erro na base de dados";